//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Start/StartSceneActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @StartSceneActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @StartSceneActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""StartSceneActions"",
    ""maps"": [
        {
            ""name"": ""candidateSelection"",
            ""id"": ""d8fbc4f1-b2ff-4147-86cc-f65ff5d4917e"",
            ""actions"": [
                {
                    ""name"": ""select"",
                    ""type"": ""Button"",
                    ""id"": ""b76ea3a7-c038-4b5d-a038-5ad23e09e4ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0291da11-e6dd-4b8a-84f5-c7d07531556a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // candidateSelection
        m_candidateSelection = asset.FindActionMap("candidateSelection", throwIfNotFound: true);
        m_candidateSelection_select = m_candidateSelection.FindAction("select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // candidateSelection
    private readonly InputActionMap m_candidateSelection;
    private List<ICandidateSelectionActions> m_CandidateSelectionActionsCallbackInterfaces = new List<ICandidateSelectionActions>();
    private readonly InputAction m_candidateSelection_select;
    public struct CandidateSelectionActions
    {
        private @StartSceneActions m_Wrapper;
        public CandidateSelectionActions(@StartSceneActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @select => m_Wrapper.m_candidateSelection_select;
        public InputActionMap Get() { return m_Wrapper.m_candidateSelection; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CandidateSelectionActions set) { return set.Get(); }
        public void AddCallbacks(ICandidateSelectionActions instance)
        {
            if (instance == null || m_Wrapper.m_CandidateSelectionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CandidateSelectionActionsCallbackInterfaces.Add(instance);
            @select.started += instance.OnSelect;
            @select.performed += instance.OnSelect;
            @select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(ICandidateSelectionActions instance)
        {
            @select.started -= instance.OnSelect;
            @select.performed -= instance.OnSelect;
            @select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(ICandidateSelectionActions instance)
        {
            if (m_Wrapper.m_CandidateSelectionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICandidateSelectionActions instance)
        {
            foreach (var item in m_Wrapper.m_CandidateSelectionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CandidateSelectionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CandidateSelectionActions @candidateSelection => new CandidateSelectionActions(this);
    public interface ICandidateSelectionActions
    {
        void OnSelect(InputAction.CallbackContext context);
    }
}
